(function(){
const API="/api/iq";let session=sessionStorage.getItem("resolvei_iq_session")||"",strategies={};
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const pct=v=>v==null?"—":Number(v).toLocaleString("pt-BR",{maximumFractionDigits:1})+"%";
async function api(path,opt={}){opt.headers=Object.assign({},opt.headers||{},session?{"X-IQ-Session":session}:{});const r=await fetch(API+path,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||"Erro no servidor.");return d}
const ui=`<div class="tool-layout iq-layout">
<section class="card panel"><div class="section-head"><div><span class="eyebrow">IQ OPTION</span><h1>📡 Análise técnica</h1><p>Análise baseada nos candles da IQ Option, com a mesma família de estratégias usada no Market Insight AI.</p></div><span class="chip" id="iqState">Desconectado</span></div>
<div class="notice"><strong>Importante:</strong> esta integração usa uma biblioteca comunitária não oficial. A senha é usada apenas para autenticar a sessão, não é salva pelo Resolvei. A ferramenta é somente de análise e não envia ordens.</div>
<div class="form-grid"><div class="field"><label>Usuário / e-mail IQ Option</label><input id="iqEmail" type="email" autocomplete="username"></div><div class="field"><label>Senha IQ Option</label><input id="iqPassword" type="password" autocomplete="current-password"></div><div class="field"><label>Conta</label><select id="iqAccount"><option value="PRACTICE">PRACTICE — Demo</option><option value="REAL">REAL — Conta real</option></select></div></div>
<div class="actions"><button class="btn primary" id="iqLogin">🔐 Autenticar</button><button class="btn" id="iqLogout">Desconectar</button></div><div id="iqMsg" class="notice" hidden></div></section>
<section class="card panel" id="iqPanel" hidden><div class="section-head"><div><span class="eyebrow">MARKET INSIGHT AI</span><h2>📊 Análise multi-timeframe</h2></div><span class="chip" id="iqBalance">Saldo: —</span></div>
<div class="form-grid"><div class="field"><label>Ativo</label><select id="iqAsset"></select></div><div class="field"><label>Estratégia</label><select id="iqStrategy"></select></div></div>
<div class="actions"><button class="btn primary" id="iqAnalyze">🔎 Analisar</button><button class="btn" id="iqRefresh">↻ Atualizar candles</button></div><div id="iqStatus" class="notice">—</div><div id="iqSignals" class="iq-signals"></div></section>
<section class="card panel" id="iqChartBox" hidden><div class="section-head"><div><span class="eyebrow">GRÁFICO</span><h2>Candles + indicadores</h2></div><span class="chip" id="iqChartInfo">—</span></div><canvas id="iqChart" height="390"></canvas></section>
<section class="card panel" id="iqDetails" hidden><span class="eyebrow">DETALHAMENTO</span><h2>Indicadores e votos</h2><div id="iqDetailsGrid" class="iq-details-grid"></div></section>
<section class="card panel"><div class="note"><strong>Leitura:</strong> CALL, PUT e AGUARDAR são saídas das regras técnicas. O acerto histórico é uma medida da amostra passada e não garante o próximo resultado.</div></section>
</div>`;

function connected(ok){document.getElementById("iqState").textContent=ok?"🟢 Conectado":"⚪ Desconectado";["iqPanel","iqChartBox","iqDetails"].forEach(id=>document.getElementById(id).hidden=!ok)}
async function setup(){if(!session){connected(false);return}try{let s=await api("/status");if(!s.connected){session="";sessionStorage.removeItem("resolvei_iq_session");connected(false);return}connected(true);document.getElementById("iqBalance").textContent="Saldo: "+(s.balance==null?"—":"R$ "+Number(s.balance).toLocaleString("pt-BR",{minimumFractionDigits:2}));let a=await api("/assets"),st=await api("/strategies");document.getElementById("iqAsset").innerHTML=a.assets.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");strategies=st.strategies;document.getElementById("iqStrategy").innerHTML=Object.entries(strategies).map(([k,v])=>`<option value="${k}">${esc(v.name)}</option>`).join("");await analyze()}catch(e){connected(false)}}
async function login(){let msg=document.getElementById("iqMsg"),btn=document.getElementById("iqLogin");msg.hidden=false;msg.textContent="⏳ Autenticando…";btn.disabled=true;try{let r=await fetch(API+"/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:document.getElementById("iqEmail").value.trim(),password:document.getElementById("iqPassword").value,account:document.getElementById("iqAccount").value})}),d=await r.json();if(!r.ok)throw Error(d.detail||"Falha no login.");session=d.session_id;sessionStorage.setItem("resolvei_iq_session",session);msg.textContent="🟢 "+d.message;connected(true);await setup()}catch(e){msg.textContent="🔴 "+e.message;connected(false)}finally{btn.disabled=false}}
async function logout(){try{await api("/logout",{method:"POST"})}catch(e){}session="";sessionStorage.removeItem("resolvei_iq_session");connected(false);document.getElementById("iqMsg").hidden=false;document.getElementById("iqMsg").textContent="Sessão desconectada."}
async function analyze(){if(!session)return;let st=document.getElementById("iqStatus");st.textContent="⏳ Analisando 1m, 5m e 15m…";try{let asset=document.getElementById("iqAsset").value,strategy=document.getElementById("iqStrategy").value;let d=await api("/analyze/"+encodeURIComponent(asset)+"?strategy="+strategy);render(d);await chart();st.textContent="✅ "+asset+" · mercado: "+(d.market||"desconhecido")}catch(e){st.textContent="⚠️ "+e.message}}
function render(d){let box=document.getElementById("iqSignals");box.innerHTML=["1min","5min","15min"].map(tf=>{let s=d.signals[tf]||{},a=s.historical_accuracy||{},c=s.signal==="CALL"?"call":s.signal==="PUT"?"put":"wait";return `<article class="iq-signal ${c}"><div class="iq-top"><b>${tf.toUpperCase()}</b><span>${esc(s.proximity?.label||"AGUARDAR")}</span></div><div class="iq-main">${esc(s.signal||"AGUARDAR")}</div><b>Score ${s.score||0} / ${strategies[d.strategy]?.max_score||0}</b><p>${esc(s.reason||"")}</p><div class="iq-meta">Acerto histórico: <b>${pct(a.rate)}</b> · Amostra: <b>${a.sample_size||0}</b> · Votos: <b>${s.resumo_votos?.bulls||0}↑ / ${s.resumo_votos?.bears||0}↓</b></div></article>`}).join("");
document.getElementById("iqDetailsGrid").innerHTML=["1min","5min","15min"].map(tf=>{let s=d.signals[tf]||{};return `<div class="iq-detail"><h3>${tf}</h3><p><b>Indicadores:</b> ${esc((s.indicators||[]).join(" · "))}</p><ul>${(s.votos||[]).map(v=>`<li><b>${esc(v.vote)}</b> — ${esc(v.name)}: ${esc(v.reason)}</li>`).join("")}</ul></div>`}).join("")}
async function chart(){try{let d=await api("/candles/"+encodeURIComponent(document.getElementById("iqAsset").value)+"?interval=300&count=180");draw(d)}catch(e){}}
function draw(d){let c=document.getElementById("iqChart");if(!d.candles?.length)return;let rows=d.candles,w=c.clientWidth||900,h=390,ratio=devicePixelRatio||1;c.width=w*ratio;c.height=h*ratio;let x=c.getContext("2d");x.scale(ratio,ratio);let p={l:45,r:15,t:15,b:25},lo=Math.min(...rows.map(r=>r.low)),hi=Math.max(...rows.map(r=>r.high)),rg=hi-lo||1,Y=v=>p.t+(hi-v)/rg*(h-p.t-p.b),X=i=>p.l+i*(w-p.l-p.r)/Math.max(1,rows.length-1);x.clearRect(0,0,w,h);rows.forEach((r,i)=>{let xx=X(i);x.beginPath();x.moveTo(xx,Y(r.high));x.lineTo(xx,Y(r.low));x.stroke();let yo=Y(r.open),yc=Y(r.close);x.fillRect(xx-2,Math.min(yo,yc),4,Math.max(1,Math.abs(yc-yo)))});["ema20","ema50","bb_upper","bb_lower"].forEach(k=>{let arr=d[k]||[];if(!arr.length)return;x.beginPath();arr.forEach((v,i)=>{let j=Math.round(i*(rows.length-1)/Math.max(1,arr.length-1));i?x.lineTo(X(j),Y(v.value)):x.moveTo(X(j),Y(v.value))});x.stroke()});document.getElementById("iqChartInfo").textContent=rows.length+" candles"})
function route(){if(!(location.hash||"").includes("analise-opcoes"))return false;let app=document.getElementById("app");if(!app)return false;app.innerHTML=ui;document.getElementById("iqLogin").onclick=login;document.getElementById("iqLogout").onclick=logout;document.getElementById("iqAnalyze").onclick=analyze;document.getElementById("iqRefresh").onclick=chart;document.getElementById("iqAsset").onchange=analyze;document.getElementById("iqStrategy").onchange=analyze;setup();return true}
let old=window.render;window.render=function(){if(!route()&&old)old()};window.addEventListener("hashchange",route);if((location.hash||"").includes("analise-opcoes"))route();
let style=document.createElement("style");style.textContent=".iq-layout{grid-template-columns:1fr 1fr}.iq-layout>section:first-child,.iq-layout>section:nth-child(2),#iqChartBox,.iq-details,.iq-layout>section:last-child{grid-column:1/-1}.iq-signals{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:16px}.iq-signal{padding:18px;border:1px solid var(--line);border-radius:16px}.iq-signal.call{border-color:var(--success)}.iq-signal.put{border-color:var(--danger)}.iq-main{font-size:30px;font-weight:800;margin:10px 0}.iq-top,.iq-meta{display:flex;justify-content:space-between;gap:10px;font-size:12px}.iq-meta{margin-top:12px;flex-wrap:wrap}.iq-details-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.iq-detail{border:1px solid var(--line);border-radius:14px;padding:15px}#iqChartBox canvas{width:100%;height:390px}@media(max-width:920px){.iq-layout{grid-template-columns:1fr}.iq-layout>section{grid-column:auto}.iq-signals,.iq-details-grid{grid-template-columns:1fr}}";document.head.appendChild(style);
})();